---
#CLACore plugin for PocketMine-MP and forks
#@Author: CLADevs Team

#-----------AUTO INV----------#
Auto-Inv: true

#-----------BROADCAST----------#
Allow-Broadcast: true

#-----------JOIN----------#
Always-Spawn: true
Title-Join: true
Allow-Guardian: true

#-----------RESPAWN----------#
Title-Respawn: true

#-----------HUNGER----------#
Disable-HungerChange: true

#-----------Rank----------#
Allow-Rank: true

#-----------NO VOID----------#
Allow-NoVoid: true
No-Void-World: world

#-----------CLEARLAGG----------#
Auto-ClearLagg: true

#-----------DEVICE----------#
#Device List:
#Android = 1, IOS = 2, Windows = 7
#Allowed-Devices:
#- 1
#- 2
#- 7
...
